export class CreatePropertyRequest {
  constructor(
    public readonly category: string,
    public readonly subCategory: any,
    public readonly purpose: string,
    public readonly completionStatus: string,
    public readonly propertyListingTitle: string,
    public readonly description: string,
    public readonly referenceNo: string,
    public readonly location: string,
    public readonly city: any,
    public readonly local: any,
    public readonly status: string,
    public readonly ownershipStatus: string,
    public readonly expiryDate: Date,
    public readonly propertyListingPrice: number,
    public readonly developerId: string,
    public readonly projectId: string,
    public readonly listingOwner: string,
    public readonly reviewStatus: string,
    public readonly propertyDocuments: string[],
    public readonly analyticsCounts: any,
    public readonly address: string,
    public readonly autoRenewal: boolean,
    public readonly renewalDate: Date,
    public readonly bedrooms: number,
    public readonly parkingSlots: number,
    public readonly currency: string,
    public readonly isFurnished: boolean,
    public readonly balcony: boolean,
    public readonly washrooms: number,
    public readonly handoverDate: Date,
    public readonly listedTimeStamp: Date,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
    public readonly deletedAt: Date,
    public readonly paidBy: string,
    public readonly paymentOptions: string,
    public readonly paymentPlan: any,
    public readonly projectTimeline: any,
    public readonly squareFeet: object,
    public readonly serviceCharge: number,
    public readonly rentalId: string,
    public readonly floorPlans: string[],
    public readonly amenities: any,
    public readonly occupancyOption: string,
    public readonly residenceType: string,
    public readonly availabilityStatus: string,
    public readonly constructionStatus: string,
    public readonly verificationService: string,
    public readonly offplanSaleType: string,
    public readonly tenancyWayOfPayments: string,
    public readonly buildingData: any,
    public readonly locationMetaData: any,
    public readonly placeId: string,
  ) {}

  toString() {
    return JSON.stringify({
      category: this.category,
      subCategory: this.subCategory,
      purpose: this.purpose,
      completionStatus: this.completionStatus,
      propertyListingTitle: this.propertyListingTitle,
      description: this.description,
      referenceNo: this.referenceNo,
      location: this.location,
      city: this.city,
      local: this.local,
      status: this.status,
      ownershipStatus: this.ownershipStatus,
      expiryDate: this.expiryDate,
      propertyListingPrice: this.propertyListingPrice,
      developerId: this.developerId,
      projectId: this.projectId,
      listingOwner: this.listingOwner,
      reviewStatus: this.reviewStatus,
      propertyDocuments: this.propertyDocuments,
      analyticsCounts: this.analyticsCounts,
      address: this.address,
      autoRenewal: this.autoRenewal,
      renewalDate: this.renewalDate,
      bedrooms: this.bedrooms,
      parkingSlots: this.parkingSlots,
      currency: this.currency,
      isFurnished: this.isFurnished,
      balcony: this.balcony,
      washrooms: this.washrooms,
      handoverDate: this.handoverDate,
      listedTimeStamp: this.listedTimeStamp,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
      deletedAt: this.deletedAt,
      paidBy: this.paidBy,
      paymentOptions: this.paymentOptions,
      paymentPlan: this.paymentPlan,
      projectTimeline: this.projectTimeline,
      squareFeet: this.squareFeet,
      serviceCharge: this.serviceCharge,
      rentalId: this.rentalId,
      floorPlans: this.floorPlans,
      amenities: this.amenities,
      occupancyOption: this.occupancyOption,
      residenceType: this.residenceType,
      availabilityStatus: this.availabilityStatus,
      constructionStatus: this.constructionStatus,
      verificationService: this.verificationService,
      offplanSaleType: this.offplanSaleType,
      tenancyWayOfPayments: this.tenancyWayOfPayments,
      buildingData: this.buildingData,
      locationMetaData: this.locationMetaData,
      placeId: this.placeId,
    });
  }
}
