export enum EVENT_TOPICS {
    ADMIN_LOGIN = 'ADMIN_LOGIN',
    ADMIN_SIGNUP = 'ADMIN_SIGNUP',
    ADMIN_CREATE_ROLE = 'ADMIN_CREATE_ROLE',
    ADMIN_UPDATE_ROLE = 'ADMIN_UPDATE_ROLE',
    ADMIN_GET_ROLES = 'ADMIN_GET_ROLES',
    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER',
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',
    RESET_PASSWORD = 'RESET_PASSWORD',
    AUTHORIZE_USER = 'AUTHORIZE_USER',
    ONBOARDING_VERIFY = 'ONBOARDING_VERIFY',
    GET_USER_DETAILS = 'GET_USER_DETAILS'
}
